version: '3.1'  # Secrets are only available since this version of Docker Compose

services:
  orthanc:
    image: jodogne/orthanc-python
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=HelloWorld
      - TZ=America/Los_Angeles
    volumes:
      - ./lua_scripts:/etc/orthanc/lua
      - orthanc-db:/var/lib/orthanc/db
      - orthanc-storage:/var/lib/orthanc/storage
    restart: always
    ports:
      - 8042:8042
      - 4242:4242

  ohif:
    image: mercureimaging/ohif
    ports:
      - 8008:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=America/Los_Angeles
    restart: always

secrets:
  orthanc.json:
    file: orthanc.json

networks:
  default:
    external: true
    name: mercure_default

volumes:
  orthanc-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/mercure/addons/orthanc/orthanc-db'
  orthanc-storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/mercure/addons/orthanc/orthanc-storage'
